services:
  app-service:
    image: cmfriend/app-service
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost}
    ports:
      - "8000:8000" 
    depends_on:
      auth-service:
        condition: service_started
  auth-service:
    image: cmfriend/auth-service
    restart: "always"
    environment:
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
 